server:
  port: 8088
  servlet:
    context-path: /ismps

#spring数据库连接配置,jsp配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.197:3309/ismps_lb?useUnicode=true&characterEncoding=utf8
    username: root
    password: gnjf123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp





#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #配置映射类所在包名
  type-aliases-package: cn.gnjf.dao.entity
  #加载Mybatis Mapper映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #加载MyBatis配置文件
  config-location: classpath:mybatis-config.xml



