server:
  port: 8088
  servlet:
    context-path: /ismps

#spring数据库连接配置,jsp配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  #resources:
    #static-locations: classpath:/webapp/WEB-INF/views






#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #配置映射类所在包名
  type-aliases-package: cn.gnjf.dao.entity
  #加载Mybatis Mapper映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #加载MyBatis配置文件
  config-location: classpath:mybatis-config.xml



