server:
  port: 8088
  servlet:
    context-path:
  tomcat:
    uri-encoding: utf-8


#spring数据库连接配置,jsp配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp




  #resources:
    #static-locations: classpath:/webapp/WEB-INF/views
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#  thymeleaf:
#    prefix: /WEB-INF/views/
#    suffix: .html






#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #配置映射类所在包名
  type-aliases-package: cn.gnjf.dao.entity
  #加载Mybatis Mapper映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #加载MyBatis配置文件
  config-location: classpath:mybatis-config.xml




#默认的文件名是：spring.log
#logging.path=./logs/mylog.log  path和file只设置一个即可,如若同时使用，则只有logging.file生效
#日志级别总共有TARCE < DEBUG < INFO < WARN < ERROR < FATAL ，
#且级别是逐渐提供，如果日志级别设置为INFO，则意味TRACE和DEBUG级别的日志都看不到
logging:
  file: springboot.log
  level:
    root: info
    cn.gnjf: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"



#%d{HH:mm:ss.SSS}——日志输出时间
#
#%thread——输出日志的进程名字，这在Web应用以及异步任务处理中很有用
#
#%-5level——日志级别，并且使用5个字符靠左对齐
#
#%logger- ——日志输出者的名字
#
#%msg——日志消息
#
#%n——平台的换行符




